UMAprotocol/optimistic-oracle-dapp

craco.config.js, src/App.tsx
Fixes issues with importing from contracts-frontend, also shows how to initialize oracle client
This needs a pending update from the sdk client to fix the exported factory
=> fix: relax strict requirements for es module imports

package.json, src/components/request/Request.tsx, src/components/request/RequestForm.tsx, src/constants/blockchain.ts, yarn.lock
1. Bump SDK version to 0.21.0
2. Swap to new flags:
InProposeState becomes CanPropose
InDisputeState becomes CanDispute
ProposalInProgress becomes ProposalTxInProgress
ApprovalInProgress becomes ApprovalTxInProgress
DisputeInProgress becomes DisputeTxInProgress
CanSettle - request is in a state the user can call settle
InDvmVote - request is wiating for dvm vote
RequestSettled - request has been settled, ie no more changes
3. Very basic Settle state (functionality not ready)
Fixed issue with links:
https://app.shortcut.com/uma-project/story/4201/instead-of-showing-the-address-of-the-proposer-and-disputer-lets-update-disputer-to-dispute-and-proposer-to-proposal-and
=> feat: Swap to new SDK flags

src/components/request/RequestForm.tsx
Adjusted parameters text when disputing.
=> fix: Change parameter language when disputing

src/components/input/Input.styled.tsx, src/components/request/RequestForm.tsx
1) Users shouldn't be allowed to input values disconnected.
https://app.shortcut.com/uma-project/story/4284/users-should-not-be-able-to-enter-values-in-input-field-when-wallet-is-not-connected
2) Users shouldn't be able to input values with insufficient funds.
https://app.shortcut.com/uma-project/story/4283/users-should-not-be-able-to-enter-numbers-in-input-field-if-they-do-not-have-enough-for-the-bond
3) Show error message with insufficient funds.
https://app.shortcut.com/uma-project/story/4321/if-users-do-not-have-enough-funds-for-proposal-bond-show-error-message
4) Remove View here link.
https://app.shortcut.com/uma-project/story/4384/remove-view-here-on-the-oo-ui-that-links-to-voter-dapp-sorry-we-are-going-back-and-forth-on-this
5) Updated design on input. …
=> fix: various CSS bug fixes

README.md, package.json, src/helpers/oracleClient.ts, src/hooks/useOracleReader.ts, yarn.lock
This bumps the sdk version and fixes the breaking changes. some minor improvements:
- use `ignoreExistenceError` built into sdk to only ignore errors where reads dont exist
- refactor `useOracleReader` to be slightly cleaner
- add env to enable debug output during development, automatically silenced in production
- increase state machine interval (from 10ms to 1ms ) in case its slightly more responsive
=> improve: update sdk, fix breaking changes, improve reader

src/components/request/Request.tsx, src/components/request/RequestHero.tsx, src/components/request/SettledTable.tsx, src/components/request/useRequestTableData.tsx, src/components/request/useSettledTableData.tsx, src/helpers/format.ts, src/hooks/useOracleReader.ts
Adds a parsed identifier to request and settle pages. adds a utility to parse identifier. 
After:
=> feat: add parsed identifier to reader, request and settle page

src/helpers/onboard.ts
This is related to this issue: https://github.com/UMAprotocol/protocol/pull/3833
Disabling this seems to silence a lot of unecessary calls to provider, and prevents spam overwhelming a local testing node.
=> fix: disable polling in ethers provider

src/components/request/Request.tsx, src/components/request/useRequestTableData.tsx, src/hooks/useOracleReader.ts
Adds the tx hash as in: https://app.shortcut.com/uma-project/story/4199/within-input-data-add-a-row-before-requestor-with-the-tx-hash-of-the-request-name-request-type-address-data-the-tx-hash-of
Signed-off-by: Gamaranto <francesco@umaproject.org>
=> feat(oo-ui): add tx hash to data

src/components/index/createRequestsTableCells.tsx, src/components/request/RequestHero.tsx, src/helpers/format.ts, src/hooks/useIsByTransactionParams.ts
Adds a utility function to parse the type of title required based on identifier. Uses this in 2 places, one in the main list of requests, and the other in the title of yes/no request details page.
=> feat: change title of yes_no_query to part of question

src/components/request/RequestForm.tsx
Error message now changes based on what status the request is in.
=> fix: improve error messages

src/components/index/createRequestsTableCells.tsx
This was not tested, but was the only instance where dispute was misspelled
=> fix: rename disput to dispute

src/components/index/createRequestsTableCells.tsx, src/components/request/useRequestTableData.tsx, src/helpers/format.ts
Previous timestamp was shown in 12 hour am/pm local time. Now its shown in 24 hour UTC time with the zone displayed. 
Edit: This was requested to remain in local 12 hour time with am/pm and show zone. 
before:
after:
note that previously the time was local to you, now it will be offset by the utc zone
=> fix: timestamp now shown in utc time

README.md, src/constants/blockchain.ts, src/constants/oracleConfig.ts, src/index.tsx
This makes a few changes to the config. To enable a specific chain, you must provider the provider url with the chain id. Enabling kovan after this update will require environment vars to add a kovan provider. Also the testing chain is disabled by removing REACT_APP_DEBUG. Previously it could not be disabled.
=> feat: add kovan option to config

src/components/index/createRequestsTableCells.tsx
Signed-off-by: amateima <amatei@umaproject.org>
Show "Unanswerable" instead of long string of characters. I filtered the requests by checking if the `proposedPrice` starts with "-". Idk if it is the right approach
---
=> fix: handle unanswerable requests

src/components/index/Index.styled.tsx, src/components/index/IndexComponent.tsx
Signed-off-by: amateima <amatei@umaproject.org>
Make the filter buttons on homepage more intuitive by adding a separate button for filtering Settled items.
=> fix: modify filter buttons

src/components/index/IndexComponent.tsx, src/components/request/useSettledTableData.tsx, src/helpers/format.ts
Titles werent being parsed when they didnt include a space after the colon in "description:" in the ancillary data.
=> fix: make title parsing a bit more permissive

package.json, src/Router.tsx, src/components/index/IndexComponent.tsx, src/components/index/RequestsTable.tsx, src/components/index/createRequestsTableCells.tsx, src/components/request/Request.tsx, src/components/request/RequestHero.tsx, src/constants/oracleConfig.ts, src/context/OracleClientContext.tsx, src/helpers/onboard.ts, src/helpers/oracleClient.ts, src/hooks/useOracleClient.ts, src/hooks/useRequestParams.ts, src/utils/format.ts, yarn.lock
This adds support for skinny OO using the updated clients.  You will notice that the factory an identical client for each contract type, and we need to know if a request resides on the regular OO or skinny OO. That means when creating URLS externally we need a new field called `oracleType` which can be one of `Skinny` or `Optimistic`
=> feat: integrate new oracle client and skinny requests

README.md, package.json, src/components/index/IndexComponent.tsx, src/components/index/createRequestsTableCells.tsx, src/components/request/useRequestTableData.tsx, src/constants/blockchain.ts, src/constants/oracleConfig.ts, src/helpers/oracleClient.ts, src/hooks/useRequestParams.ts, yarn.lock
**Motivation**
Add in support for many more chains
**Summary**
This adds support for OPTIMISM, METER, XDAI, SX, EVMOS,ARBITRUM, AVAX. Addresses are made explicit in this config to make it easy to double check for errors. All addresses were obtained from the [networks files](https://github.com/UMAprotocol/protocol/tree/master/packages/core/networks), except for goerli, which was obtained from a [yet to be merged pr](https://github.com/UMAprotocol/protocol/pull/4056). EDIT: john has provided the updated goerli addresses which no longer match this pr.
Pay special attention when reviewing to chain constants, as these had to be searched and investigated to find things like currency symbols, names, explorers.  Most currency logos are scaffolded with …
=> feat: add support for many new chains

src/components/index/createRequestsTableCells.tsx, src/hooks/useRequestParams.ts
This changes the url linked from the index page to use the transaction hash rather than ancillary data. this is needed so we can use url shortners and copy and paste it into other places when ancillary data is too long
=> improve: use shorter links in oo ui

package.json, src/components/index/createRequestsTableCells.tsx, src/components/request/Request.tsx, src/helpers/oracleClient.ts, src/hooks/useOracleClient.ts, yarn.lock
This bumps the sdk version to fix the problem with not being able to load skinny OO requests by transaction hash. Also makes tranasction hash loading a bit more robust
=> fix: make selecting request by tx hash more robust

README.md, src/constants/blockchain.ts, src/constants/oracleConfig.ts
This PR adds support for mumbai. A few hackathon teams have asked for mumbai support along with Polymarket using mumbai for testing.
When I tested I included the rpc url as an env variable but is there any action needed to include in vercel deployment?
=> feat: add support for Mumbai

src/components/request/useRequestTableData.tsx, src/hooks/useOptimisticGovernorRules.ts
Signed-off-by: Alex Gaines <againes@umaproject.org>
This PR includes the `explanation` for Zodiac proposals. For Snapshot proposals, the IPFS hash is included as the explanation which can be used as a unique identifier for proposals. Including it in the OO UI will make the verification process easier.
=> improve: add explanation to zodiac proposals
