src/components/navbar/Navbar.tsx
src/hooks/useOnboard.ts

walletCheck() is required to connect the app for the first time so it must be in.

add walletcheck back in.

---

src/components/request/RequestForm.tsx

Remove form validation for negative numbers (Magic Number which is a negative number is a possible answer).
Story details: https://app.shortcut.com/uma-project/story/4392

fix: Lets users type a negative value in input field on OO UI

---

src/components/request/RequestHero.tsx

fix: show proper tag for dispute state

---

vercel.json

Signed-off-by: Evaldo Felipe <contato@evaldofelipe.com>

Add headers

---

src/components/global-styles/GlobalStyles.tsx
src/components/request/Request.styled.tsx
src/components/request/SettledTable.tsx

Font definitions adjusted to match Umaverse.

fix: updated fonts.

---

src/components/request/Request.styled.tsx
src/components/request/RequestHero.tsx

story: https://app.shortcut.com/uma-project/story/4553/ability-to-view-the-tx-hash-of-the-request
Added request tx url.

feat: add request tx hash 

---

src/components/request/useRequestTableData.tsx

Story details: https://app.shortcut.com/uma-project/story/4412

fix: change text to UMIP

---

src/components/index/Index.styled.tsx
src/components/wrappers/Wrappers.tsx

Adjusted margins a bit on the sides, lmk if that's ok @Tommy1231232 
https://app.shortcut.com/uma-project/story/4288/interface-is-too-zoomed-in-on-smaller-screen-sizes

fix: adjusted margins of index

---

src/components/request/RequestForm.tsx

Fixes https://app.shortcut.com/uma-project/story/4354/update-the-view-of-the-input-box-when-the-request-is-going-through-a-dispute-period , i tried for a while to repro a proposed price but couldn't so lets play extra attention when qaing this
Signed-off-by: Gamaranto <francesco@umaproject.org>

fix(oo-ui): update dispute ui

---

src/components/index/createRequestsTableCells.tsx

Fix: https://app.shortcut.com/uma-project/story/4686/sort-requests-on-index-page-by-timestamp-newest-to-oldest
Signed-off-by: Gamaranto <francesco@umaproject.org>

fix(oo-ui): improve formatting

---

src/components/request/Request.tsx
src/constants/oracleConfig.ts
src/helpers/oracleClient.ts
src/hooks/useIsByTransactionParams.ts

fix: clear out request data from page until fully loaded

---

src/components/index/createRequestsTableCells.tsx
src/components/request/useRequestTableData.tsx

fix: rename timestamp to request timestamp in tables

---

src/components/index/Index.styled.tsx
src/components/index/IndexComponent.tsx
src/components/index/RequestsTable.tsx
src/components/layout/Layout.styled.tsx
src/components/navbar/Navbar.styled.tsx
src/components/request/Request.styled.tsx
src/utils/format.ts

Add filter button row.
https://app.shortcut.com/uma-project/story/5095/create-a-filter-button-on-oo-ui-home-page

feat: filter button row for OO

---

src/components/index/IndexComponent.tsx

feat: Change checkbox to Hide Settled

---

src/components/index/IndexComponent.tsx

fix: merge settled data if unchecked

---

src/components/index/IndexComponent.tsx

feat: sort OO by timestamp

---

package.json
src/Router.tsx
src/assets/Pagination-left-arrow.svg
src/assets/Pagination-right-arrow.svg
src/components/index/IndexComponent.tsx
src/components/index/PageNavigation.tsx
src/components/index/RequestsTableWithPagination.tsx
src/constants/oracleConfig.ts
src/utils/paginate.ts
tsconfig.json
yarn.lock

This does not have back/ forward buttons because it doesnt need it. if this behavior is bad then can use jasons technique. 
updated: 
updated:

feat: add basic pagination for index page

---

src/components/index/IndexComponent.tsx
src/components/index/PageNavigation.tsx
src/components/index/RequestsTableWithPagination.tsx
src/utils/paginate.ts
tsconfig.json

fixed type errors.

---

src/components/index/Index.styled.tsx

fix: Css fixes

---

src/components/index/createRequestsTableCells.tsx
src/components/request/Loading.tsx
src/components/request/Request.styled.tsx
src/components/request/Request.tsx

This waits for request command to finish loading before showing request details. adds loading indicator while wwaiting. Note, this does not match the design perfectly due to limitations of working with font-awesome fonts.

feat: add request loading logic

---

package.json
src/components/index/IndexComponent.tsx
src/constants/oracleConfig.ts
src/hooks/useOracleReader.ts
yarn.lock

Tweaks how polygon loads requests to get initial results faster at the expense of overall slower history loading

chore: improve polygon loading performance

---

src/components/index/IndexComponent.tsx

Signed-off-by: amateima <amatei@umaproject.org>

feat: hide request older than 1 month

---

package.json
yarn.lock

This improves performance for loading request details, and caches details to so revisiting a request loads faster
You should see performance improvements when selecting to view specific requests, and when re-visiting requests you already have loaded, compare this to performance of production app.

improve: bump sdk version

---

package.json
src/constants/blockchain.ts
src/constants/oracleConfig.ts
src/helpers/oracleClient.ts
src/hooks/useOracleReader.ts
src/hooks/useRequestParams.ts
yarn.lock

This adds optimistic oracle v2 client as well as goerli deployments.  Once this is in we can update our deployed urls for goerli.

feat: add oracle v1/ v2 goreli

---

package.json
src/Router.tsx
yarn.lock

chore: bump sdk for some fixes

---

src/components/request/RequestForm.tsx
src/components/request/RequestHero.tsx
src/hooks/useOracleReader.ts

Adds event based expiry logic. Shows a pill and prevents people from proposing early expiry when the request is "event based" which may be hard to find in actual requests.

feat: add event based logic

---

src/components/index/IndexComponent.tsx
src/components/select/Select.styled.tsx
src/constants/oracleConfig.ts

This adds a very simple dropdown filter for the chain you want to see.

feat: add chain based filtering to index page

---

src/components/request/useRequestTableData.tsx
src/hooks/useOptimisticGovernorRules.ts
src/hooks/useOracleReader.ts

Signed-off-by: Alex Gaines <againes@umaproject.org>
This PR adds optimistic governor rules for applicable requests:

feat: add rules for optimistic governor requests

---

src/components/index/IndexComponent.tsx
src/components/select/Select.styled.tsx
src/components/select/Select.tsx

feat: add request count to chain dropdown

---

src/components/index/IndexComponent.tsx

Ignore event based requests when filtering by age.

feat: ignore event based requests when filtering by time

---

package.json
src/components/index/RequestsTable.styled.tsx
src/components/index/createRequestsTableCells.tsx
src/components/table/Table.styled.tsx
yarn.lock

This adds a column on the index page to show event based expiry. Columns needed to be adjusted to fit better. It takes time to load event based data, so if the data isnt available it will show `-` until it loads.

feat: add event based expiry column to index table

---

package.json
src/components/index/Index.styled.tsx
src/components/index/IndexComponent.tsx
yarn.lock

This adds a checkbox to show/hide event based expiry requests from the index page.

feat: add toggle for hiding event based expiry requests

---

src/components/table/Table.styled.tsx

fix: wrap anc data cell in table
